export const KanbanCardSeed = [
  {
    title: 'Task 1',
    lane: 1,
    order: 1,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 2',
    lane: 1,
    order: 2,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 3',
    lane: 1,
    order: 3,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 4',
    lane: 1,
    order: 4,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 5',
    lane: 1,
    order: 5,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 6',
    lane: 1,
    order: 6,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 1',
    lane: 2,
    order: 1,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },
  {
    title: 'Task 2',
    lane: 2,
    order: 2,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },
  {
    title: 'Task 3',
    lane: 2,
    order: 3,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },
  {
    title: 'Task 4',
    lane: 2,
    order: 4,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },
  {
    title: 'Task 5',
    lane: 2,
    order: 5,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },
  {
    title: 'Task 6',
    lane: 2,
    order: 6,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },
  {
    title: 'Task 1',
    lane: 3,
    order: 1,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 2',
    lane: 3,
    order: 2,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 3',
    lane: 3,
    order: 3,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 4',
    lane: 3,
    order: 4,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 5',
    lane: 3,
    order: 5,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 6',
    lane: 3,
    order: 6,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
];
