export const KanbanCardSeed = [
  {
    title: 'Task 1',
    projectId: 1,
    laneId: 1,
    order: 1,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 2',
    projectId: 1,
    laneId: 1,
    order: 2,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 3',
    projectId: 1,
    laneId: 1,
    order: 3,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 4',
    projectId: 1,
    laneId: 1,
    order: 4,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 5',
    projectId: 1,
    laneId: 2,
    order: 1,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 6',
    projectId: 1,
    laneId: 2,
    order: 2,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 7',
    projectId: 1,
    laneId: 2,
    order: 3,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 8',
    projectId: 1,
    laneId: 2,
    order: 4,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 9',
    projectId: 1,
    laneId: 3,
    order: 1,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
  {
    title: 'Task 10',
    projectId: 1,
    laneId: 3,
    order: 2,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },

  {
    title: 'Task 11',
    projectId: 2,
    laneId: 1,
    order: 1,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },
  {
    title: 'Task 12',
    projectId: 2,
    laneId: 1,
    order: 2,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },
  {
    title: 'Task 13',
    projectId: 2,
    laneId: 1,
    order: 3,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },
  {
    title: 'Task 14',
    projectId: 2,
    laneId: 1,
    order: 4,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },
  {
    title: 'Task 15',
    projectId: 2,
    laneId: 2,
    order: 1,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },
  {
    title: 'Task 16',
    projectId: 2,
    laneId: 2,
    order: 2,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },
  {
    title: 'Task 17',
    projectId: 2,
    laneId: 2,
    order: 3,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },
  {
    title: 'Task 18',
    projectId: 2,
    laneId: 2,
    order: 4,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },
  {
    title: 'Task 19',
    projectId: 2,
    laneId: 3,
    order: 1,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },
  {
    title: 'Task 20',
    projectId: 2,
    laneId: 3,
    order: 2,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },
  {
    title: 'Task 1',
    projectId: 3,
    laneId: 1,
    order: 1,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },
  {
    title: 'Task 2',
    projectId: 3,
    laneId: 1,
    order: 2,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },
  {
    title: 'Task 3',
    projectId: 3,
    laneId: 1,
    order: 3,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },

  {
    title: 'Task 4',
    projectId: 3,
    laneId: 1,
    order: 4,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'Jane Doe',
  },

  {
    title: 'Task 5',
    projectId: 3,
    laneId: 2,
    order: 1,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },

  {
    title: 'Task 6',
    projectId: 3,
    laneId: 2,
    order: 2,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },

  {
    title: 'Task 7',
    projectId: 3,
    laneId: 2,
    order: 3,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },

  {
    title: 'Task 8',
    projectId: 3,
    laneId: 2,
    order: 4,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },

  {
    title: 'Task 9',
    projectId: 3,
    laneId: 3,
    order: 1,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },

  {
    title: 'Task 10',
    projectId: 3,
    laneId: 3,
    order: 2,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assignee: 'John Doe',
  },
];
