export const KanbanCardSeed = [
  {
    title: 'Contact Tesla about bug',
    projectId: 1,
    laneId: 1,
    order: 1,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assigneeId: 5,
    tags: ['lead', 'bug'],
  },
  {
    title: 'Contact SpaceX about landing system',
    projectId: 1,
    laneId: 1,
    order: 2,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assigneeId: 3,
    tags: ['lead', 'software'],
  },
  {
    title: 'Contact Google about redoing the search engine',
    projectId: 1,
    laneId: 1,
    order: 3,
    description: 'This is a description',
    startDate: new Date(),
    dueDate: new Date(),
    assigneeId: 10,
    tags: ['lead', 'software'],
  },
];
