export const KanbanLaneSeed = [
  {
    id: 1,
    projectId: 1,
    title: 'Backlog',
    order: 1,
    borderColor: '#ff0000',
  },
  {
    id: 2,
    projectId: 1,
    title: 'To Do',
    order: 2,
    borderColor: '#00ff00',
  },
  {
    id: 3,
    projectId: 1,
    title: 'In Progress',
    order: 3,
    borderColor: '#0000ff',
  },
  {
    id: 4,
    projectId: 1,
    title: 'Done',
    order: 4,
    borderColor: '#ffff00',
  },
  {
    id: 5,
    projectId: 2,
    title: 'Backlog',
    order: 1,
    borderColor: '#ff0000',
  },
  {
    id: 6,
    projectId: 2,
    title: 'To Do',
    order: 2,
    borderColor: '#00ff00',
  },
  {
    id: 7,
    projectId: 2,
    title: 'In Progress',
    order: 3,
    borderColor: '#0000ff',
  },
  {
    id: 8,
    projectId: 2,
    title: 'Done',
    order: 4,
    borderColor: '#ffff00',
  },
  {
    id: 9,
    projectId: 3,
    title: 'Backlog',
    order: 1,
    borderColor: '#ff0000',
  },
  {
    id: 10,
    projectId: 3,
    title: 'To Do',
    order: 2,
    borderColor: '#00ff00',
  },
  {
    id: 11,
    projectId: 3,
    title: 'In Progress',
    order: 3,
    borderColor: '#0000ff',
  },
  {
    id: 12,
    projectId: 3,
    title: 'Done',
    order: 4,
    borderColor: '#ffff00',
  },
];
